apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qzwvtf7tm-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qzwvtf7tm-java-springboot-gitops